In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("🩸 Halo Care Feminine Hygiene Survey .csv")

In [3]:
df.columns

Index(['Entry_id', 'What is your age?', 'What city do you live in? ',
       'What is your current occupation? ',
       'What is your monthly income range? ',
       'What type of menstrual product(s) do you currently use? (Select all that apply) ',
       'Which brand(s) of sanitary pads do you currently use or trust? (Select all that apply) ',
       'How satisfied are you with your current menstrual care products? ',
       'What do you care most about when choosing a menstrual product? (Pick top 3) ',
       'Would you be interested in trying a new Nigerian-made menstrual care brand designed with softness; comfort; and clean packaging? ',
       'Would you consider using reusable pads or eco-conscious period products? ',
       'Which of the following products would you like to see included in your ideal period care pack? (Select all that apply) ',
       'What price would you consider fair for a pack of high-quality sanitary pads (10 pads)? ',
       'Where do you usually buy your menstrual products? ',
       'Would you consider ordering menstrual products through an app or website with a monthly subscription option? ',
       'Are you open to receiving health and period care tips from a brand on WhatsApp or Instagram? ',
       'If you could tell a menstrual care brand one thing to improve your experience; what would it be?'],
      dtype='object')

In [4]:
responses = df['If you could tell a menstrual care brand one thing to improve your experience; what would it be?']

In [6]:
type(responses)

pandas.core.series.Series

In [7]:
# Define themes and associated keywords for classification
themes_keywords = {
    "Comfort & Skin Sensitivity": ["comfortable", "comfort", "soft", "skin", "irritation", "sensitive", "abrasive", "rash", "reaction"],
    "Length, Width & Coverage": ["length", "long", "wider", "expand", "coverage", "sizeable", "roll over", "body types"],
    "Adhesive/Gum Quality (Stickiness)": ["gum", "stick", "adhesive", "wings", "hold", "glue", "panties", "underwear"],
    "Absorbency & Leak Protection": ["absorbent", "absorbency", "leak", "drip", "flow", "heavier", "soak", "protect"],
    "Affordability & Accessibility": ["affordable", "cheap", "price", "expensive", "accessible", "cost"],
    "Product Variety": ["night", "heavy flow", "liners", "variety", "options", "sizes", "different types"],
    "Sustainability & Materials": ["eco", "sustainable", "recyclable", "non-toxic", "organic", "materials", "fragrance-free"],
    "Pain Relief & Extra Features": ["pain", "relief", "menthol", "soothing", "cooling", "heating", "extra", "features", "educational"],
    "Positive Feedback / No Issues / Nil": ["nil", "keep up", "nothing", "good work"]
}

In [8]:
# Function to classify each response
def classify_response(response, theme_keywords):
    response_lower = response.lower()
    matched_themes = []
    for theme, keywords in theme_keywords.items():
        if any(keyword in response_lower for keyword in keywords):
            matched_themes.append(theme)
    return matched_themes if matched_themes else ["Unclassified"]

# Classify all responses
classified_data = []
for resp in responses:
    themes = classify_response(resp, themes_keywords)
    classified_data.append({"Response": resp, "Themes": themes})

In [13]:
# Create a DataFrame
df1 = pd.DataFrame(classified_data)

In [14]:
df1

,Response,Themes
0,The problem I have with a lot of brands is the...,"[Comfort & Skin Sensitivity, Sustainability & ..."
1,pay attention to length; stickiness and width ...,"[Length, Width & Coverage, Adhesive/Gum Qualit..."
2,Length of pad. Make it longer,"[Length, Width & Coverage]"
3,.,[Unclassified]
4,It should always be comfortable and to feel sa...,[Comfort & Skin Sensitivity]
...,...,...
94,Make length longer and consider women with hea...,"[Length, Width & Coverage, Absorbency & Leak P..."
95,Comfort; flatness and skin friendly,[Comfort & Skin Sensitivity]
96,Nil,[Positive Feedback / No Issues / Nil]
97,Nothing really at the moment,[Positive Feedback / No Issues / Nil]
98,Comfort,[Comfort & Skin Sensitivity]

In [16]:
# Expand themes into comma-separated string for readability
df1["Themes"] = df1["Themes"].apply(lambda x: "; ".join(x))

df1

,Response,Themes
0,The problem I have with a lot of brands is the...,Comfort & Skin Sensitivity; Sustainability & M...
1,pay attention to length; stickiness and width ...,"Length, Width & Coverage; Adhesive/Gum Quality..."
2,Length of pad. Make it longer,"Length, Width & Coverage"
3,.,Unclassified
4,It should always be comfortable and to feel sa...,Comfort & Skin Sensitivity
...,...,...
94,Make length longer and consider women with hea...,"Length, Width & Coverage; Absorbency & Leak Pr..."
95,Comfort; flatness and skin friendly,Comfort & Skin Sensitivity
96,Nil,Positive Feedback / No Issues / Nil
97,Nothing really at the moment,Positive Feedback / No Issues / Nil
98,Comfort,Comfort & Skin Sensitivity

In [17]:
from collections import Counter

# Flatten the list of all themes
all_themes = sum((classify_response(resp, themes_keywords) for resp in responses), [])
theme_counts = Counter(all_themes)

# Convert to a DataFrame for easy display
theme_summary = pd.DataFrame(theme_counts.items(), columns=["Theme", "Count"]).sort_values(by="Count", ascending=False)
theme_summary

                                 Theme  Count
0           Comfort & Skin Sensitivity     38
2             Length, Width & Coverage     21
3    Adhesive/Gum Quality (Stickiness)     20
6         Absorbency & Leak Protection     15
9        Affordability & Accessibility     12
4                         Unclassified     10
8                      Product Variety     10
1           Sustainability & Materials      8
7         Pain Relief & Extra Features      7
5  Positive Feedback / No Issues / Nil      5

In [19]:
df["Themes"] = df1["Themes"]
df

,Entry_id,What is your age?,What city do you live in?,What is your current occupation?,What is your monthly income range?,What type of menstrual product(s) do you currently use? (Select all that apply),Which brand(s) of sanitary pads do you currently use or trust? (Select all that apply),How satisfied are you with your current menstrual care products?,What do you care most about when choosing a menstrual product? (Pick top 3),Would you be interested in trying a new Nigerian-made menstrual care brand designed with softness; comfort; and clean packaging?,Would you consider using reusable pads or eco-conscious period products?,Which of the following products would you like to see included in your ideal period care pack? (Select all that apply),What price would you consider fair for a pack of high-quality sanitary pads (10 pads)?,Where do you usually buy your menstrual products?,Would you consider ordering menstrual products through an app or website with a monthly subscription option?,Are you open to receiving health and period care tips from a brand on WhatsApp or Instagram?,If you could tell a menstrual care brand one thing to improve your experience; what would it be?,Themes
0,1,25-34,Enugu,Unemployed,Below #30;000,Disposable pads,Softcare,Satisfied,Price;Comfort;Absorbency;Skin sensitivity;Avai...,Yes,Maybe; if I understood them better,Day sanitary pads;Night pads;Tampons;Wipes;Hea...,#500 - #800,Through a vendor/shop nearby,Maybe,Maybe,The problem I have with a lot of brands is the...,Comfort & Skin Sensitivity; Sustainability & M...
1,2,19-24,Port Harcourt,Self-employed,#100;000 - #200;000,Disposable pads;Pantyliners,Molped;bisense,Satisfied,Comfort;Absorbency;Skin sensitivity;Brand repu...,Yes,No,Day sanitary pads;Night pads;Wipes;Disposable ...,#801 - #1;200,Supermarket,No,Maybe,pay attention to length; stickiness and width ...,"Length, Width & Coverage; Adhesive/Gum Quality..."
2,3,25-34,Enugu,Employed,#100;000 - #200;000,Disposable pads,Soft,Very satisfied,Price;Comfort;Absorbency;Skin sensitivity,Maybe,Maybe; if I understood them better,Night pads;Disposable underwear;Heating pad fo...,#500 - #800,Supermarket,Maybe,Yes,Length of pad. Make it longer,"Length, Width & Coverage"
3,4,19-24,Port Harcourt,Student,#61;000 - #100;000,Disposable pads,Soft care,Satisfied,Price;Comfort;Skin sensitivity,Yes,No,Day sanitary pads;Night pads;Heating pad for c...,#801 - #1;200,Through a vendor/shop nearby,Maybe,Yes,.,Unclassified
4,5,19-24,Lagos,Student,Below #30;000,Disposable pads,Besense,Satisfied,Comfort;Absorbency,Yes,Maybe; if I understood them better,Day sanitary pads;Night pads;Disposable underwear,#801 - #1;200,Through a vendor/shop nearby,Maybe,Yes,It should always be comfortable and to feel sa...,Comfort & Skin Sensitivity
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,25-34,Abuja,Employed,#100;000 - #200;000,Disposable pads;Pantyliners,Always;LadyCare;Molped;Virony;Bisense; Softcare,Very satisfied,Price;Comfort;Absorbency;Skin sensitivity,Yes,Yes,Day sanitary pads;Wipes;Herbal teas for PMS,#500 - #800,Supermarket,No,Yes,Make length longer and consider women with hea...,"Length, Width & Coverage; Absorbency & Leak Pr..."
95,96,25-34,Abuja,Unemployed,Over #200;000,Disposable pads;Tampons;Pantyliners,Always;Virony;Aya;,Unsatisfied,Price;Comfort;Skin sensitivity,Yes,No,Day sanitary pads;Night pads;Tampons;Wipes;Hea...,#500 - #800,Supermarket,Maybe,Maybe,Comfort; flatness and skin friendly,Comfort & Skin Sensitivity
96,97,25-34,Lagos,Employed,#100;000 - #200;000,Disposable pads;Pantyliners,Lilypad,Satisfied,Price;Comfort;Absorbency;Skin sensitivity,Yes,Maybe; if I understood them better,Day sanitary pads;Night pads;Wipes;Disposable ...,#801 - #1;200,Supermarket,Yes,No,Nil,Positive Feedback / No Issues / Nil
97,98,25-34,Enugu,Employed,#100;000 - #200;000,Disposable pads;Pantyliners,Molped;Virony;Softcare,Very satisfied,Comfort;Absorbency;Skin sensitivity;Availabili...,Maybe,Maybe; if I understood them better,Day sanitary pads;Night pads;Wipes;Disposable ...,#801 - #1;200,Supermarket,Maybe,Yes,Nothing really at the moment,Positive Feedback / No Issues / Nil
98,99,25-34,Abuja,Employed,#100;000 - #200;000,Disposable pads,Softcare,Very satisfied,Comfort;Absorbency;Skin sensitivity,Maybe,No,Day sanitary pads;Night pads;Wipes;Disposable ...,Over #1;200,Supermarket,Maybe,Maybe,Comfort,Comfort & Skin Sensitivity

In [20]:
df.columns

Index(['Entry_id', 'What is your age?', 'What city do you live in? ',
       'What is your current occupation? ',
       'What is your monthly income range? ',
       'What type of menstrual product(s) do you currently use? (Select all that apply) ',
       'Which brand(s) of sanitary pads do you currently use or trust? (Select all that apply) ',
       'How satisfied are you with your current menstrual care products? ',
       'What do you care most about when choosing a menstrual product? (Pick top 3) ',
       'Would you be interested in trying a new Nigerian-made menstrual care brand designed with softness; comfort; and clean packaging? ',
       'Would you consider using reusable pads or eco-conscious period products? ',
       'Which of the following products would you like to see included in your ideal period care pack? (Select all that apply) ',
       'What price would you consider fair for a pack of high-quality sanitary pads (10 pads)? ',
       'Where do you usually buy your menstrual products? ',
       'Would you consider ordering menstrual products through an app or website with a monthly subscription option? ',
       'Are you open to receiving health and period care tips from a brand on WhatsApp or Instagram? ',
       'If you could tell a menstrual care brand one thing to improve your experience; what would it be?',
       'Themes'],
      dtype='object')

In [21]:
# Step 1: First, split the semicolon-separated themes into a list
df["Themes"] = df["Themes"].str.split("; ")

In [22]:
df

,Entry_id,What is your age?,What city do you live in?,What is your current occupation?,What is your monthly income range?,What type of menstrual product(s) do you currently use? (Select all that apply),Which brand(s) of sanitary pads do you currently use or trust? (Select all that apply),How satisfied are you with your current menstrual care products?,What do you care most about when choosing a menstrual product? (Pick top 3),Would you be interested in trying a new Nigerian-made menstrual care brand designed with softness; comfort; and clean packaging?,Would you consider using reusable pads or eco-conscious period products?,Which of the following products would you like to see included in your ideal period care pack? (Select all that apply),What price would you consider fair for a pack of high-quality sanitary pads (10 pads)?,Where do you usually buy your menstrual products?,Would you consider ordering menstrual products through an app or website with a monthly subscription option?,Are you open to receiving health and period care tips from a brand on WhatsApp or Instagram?,If you could tell a menstrual care brand one thing to improve your experience; what would it be?,Themes
0,1,25-34,Enugu,Unemployed,Below #30;000,Disposable pads,Softcare,Satisfied,Price;Comfort;Absorbency;Skin sensitivity;Avai...,Yes,Maybe; if I understood them better,Day sanitary pads;Night pads;Tampons;Wipes;Hea...,#500 - #800,Through a vendor/shop nearby,Maybe,Maybe,The problem I have with a lot of brands is the...,"[Comfort & Skin Sensitivity, Sustainability & ..."
1,2,19-24,Port Harcourt,Self-employed,#100;000 - #200;000,Disposable pads;Pantyliners,Molped;bisense,Satisfied,Comfort;Absorbency;Skin sensitivity;Brand repu...,Yes,No,Day sanitary pads;Night pads;Wipes;Disposable ...,#801 - #1;200,Supermarket,No,Maybe,pay attention to length; stickiness and width ...,"[Length, Width & Coverage, Adhesive/Gum Qualit..."
2,3,25-34,Enugu,Employed,#100;000 - #200;000,Disposable pads,Soft,Very satisfied,Price;Comfort;Absorbency;Skin sensitivity,Maybe,Maybe; if I understood them better,Night pads;Disposable underwear;Heating pad fo...,#500 - #800,Supermarket,Maybe,Yes,Length of pad. Make it longer,"[Length, Width & Coverage]"
3,4,19-24,Port Harcourt,Student,#61;000 - #100;000,Disposable pads,Soft care,Satisfied,Price;Comfort;Skin sensitivity,Yes,No,Day sanitary pads;Night pads;Heating pad for c...,#801 - #1;200,Through a vendor/shop nearby,Maybe,Yes,.,[Unclassified]
4,5,19-24,Lagos,Student,Below #30;000,Disposable pads,Besense,Satisfied,Comfort;Absorbency,Yes,Maybe; if I understood them better,Day sanitary pads;Night pads;Disposable underwear,#801 - #1;200,Through a vendor/shop nearby,Maybe,Yes,It should always be comfortable and to feel sa...,[Comfort & Skin Sensitivity]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,25-34,Abuja,Employed,#100;000 - #200;000,Disposable pads;Pantyliners,Always;LadyCare;Molped;Virony;Bisense; Softcare,Very satisfied,Price;Comfort;Absorbency;Skin sensitivity,Yes,Yes,Day sanitary pads;Wipes;Herbal teas for PMS,#500 - #800,Supermarket,No,Yes,Make length longer and consider women with hea...,"[Length, Width & Coverage, Absorbency & Leak P..."
95,96,25-34,Abuja,Unemployed,Over #200;000,Disposable pads;Tampons;Pantyliners,Always;Virony;Aya;,Unsatisfied,Price;Comfort;Skin sensitivity,Yes,No,Day sanitary pads;Night pads;Tampons;Wipes;Hea...,#500 - #800,Supermarket,Maybe,Maybe,Comfort; flatness and skin friendly,[Comfort & Skin Sensitivity]
96,97,25-34,Lagos,Employed,#100;000 - #200;000,Disposable pads;Pantyliners,Lilypad,Satisfied,Price;Comfort;Absorbency;Skin sensitivity,Yes,Maybe; if I understood them better,Day sanitary pads;Night pads;Wipes;Disposable ...,#801 - #1;200,Supermarket,Yes,No,Nil,[Positive Feedback / No Issues / Nil]
97,98,25-34,Enugu,Employed,#100;000 - #200;000,Disposable pads;Pantyliners,Molped;Virony;Softcare,Very satisfied,Comfort;Absorbency;Skin sensitivity;Availabili...,Maybe,Maybe; if I understood them better,Day sanitary pads;Night pads;Wipes;Disposable ...,#801 - #1;200,Supermarket,Maybe,Yes,Nothing really at the moment,[Positive Feedback / No Issues / Nil]
98,99,25-34,Abuja,Employed,#100;000 - #200;000,Disposable pads,Softcare,Very satisfied,Comfort;Absorbency;Skin sensitivity,Maybe,No,Day sanitary pads;Night pads;Wipes;Disposable ...,Over #1;200,Supermarket,Maybe,Maybe,Comfort,[Comfort & Skin Sensitivity]

In [23]:
# Step 2: Use explode to unnest the themes so each row has only one theme
df_exploded = df.explode("Themes").reset_index(drop=True)

In [24]:
df_exploded

,Entry_id,What is your age?,What city do you live in?,What is your current occupation?,What is your monthly income range?,What type of menstrual product(s) do you currently use? (Select all that apply),Which brand(s) of sanitary pads do you currently use or trust? (Select all that apply),How satisfied are you with your current menstrual care products?,What do you care most about when choosing a menstrual product? (Pick top 3),Would you be interested in trying a new Nigerian-made menstrual care brand designed with softness; comfort; and clean packaging?,Would you consider using reusable pads or eco-conscious period products?,Which of the following products would you like to see included in your ideal period care pack? (Select all that apply),What price would you consider fair for a pack of high-quality sanitary pads (10 pads)?,Where do you usually buy your menstrual products?,Would you consider ordering menstrual products through an app or website with a monthly subscription option?,Are you open to receiving health and period care tips from a brand on WhatsApp or Instagram?,If you could tell a menstrual care brand one thing to improve your experience; what would it be?,Themes
0,1,25-34,Enugu,Unemployed,Below #30;000,Disposable pads,Softcare,Satisfied,Price;Comfort;Absorbency;Skin sensitivity;Avai...,Yes,Maybe; if I understood them better,Day sanitary pads;Night pads;Tampons;Wipes;Hea...,#500 - #800,Through a vendor/shop nearby,Maybe,Maybe,The problem I have with a lot of brands is the...,Comfort & Skin Sensitivity
1,1,25-34,Enugu,Unemployed,Below #30;000,Disposable pads,Softcare,Satisfied,Price;Comfort;Absorbency;Skin sensitivity;Avai...,Yes,Maybe; if I understood them better,Day sanitary pads;Night pads;Tampons;Wipes;Hea...,#500 - #800,Through a vendor/shop nearby,Maybe,Maybe,The problem I have with a lot of brands is the...,Sustainability & Materials
2,2,19-24,Port Harcourt,Self-employed,#100;000 - #200;000,Disposable pads;Pantyliners,Molped;bisense,Satisfied,Comfort;Absorbency;Skin sensitivity;Brand repu...,Yes,No,Day sanitary pads;Night pads;Wipes;Disposable ...,#801 - #1;200,Supermarket,No,Maybe,pay attention to length; stickiness and width ...,"Length, Width & Coverage"
3,2,19-24,Port Harcourt,Self-employed,#100;000 - #200;000,Disposable pads;Pantyliners,Molped;bisense,Satisfied,Comfort;Absorbency;Skin sensitivity;Brand repu...,Yes,No,Day sanitary pads;Night pads;Wipes;Disposable ...,#801 - #1;200,Supermarket,No,Maybe,pay attention to length; stickiness and width ...,Adhesive/Gum Quality (Stickiness)
4,3,25-34,Enugu,Employed,#100;000 - #200;000,Disposable pads,Soft,Very satisfied,Price;Comfort;Absorbency;Skin sensitivity,Maybe,Maybe; if I understood them better,Night pads;Disposable underwear;Heating pad fo...,#500 - #800,Supermarket,Maybe,Yes,Length of pad. Make it longer,"Length, Width & Coverage"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,95,25-34,Abuja,Employed,#100;000 - #200;000,Disposable pads;Pantyliners,Always;LadyCare;Molped;Virony;Bisense; Softcare,Very satisfied,Price;Comfort;Absorbency;Skin sensitivity,Yes,Yes,Day sanitary pads;Wipes;Herbal teas for PMS,#500 - #800,Supermarket,No,Yes,Make length longer and consider women with hea...,Product Variety
142,96,25-34,Abuja,Unemployed,Over #200;000,Disposable pads;Tampons;Pantyliners,Always;Virony;Aya;,Unsatisfied,Price;Comfort;Skin sensitivity,Yes,No,Day sanitary pads;Night pads;Tampons;Wipes;Hea...,#500 - #800,Supermarket,Maybe,Maybe,Comfort; flatness and skin friendly,Comfort & Skin Sensitivity
143,97,25-34,Lagos,Employed,#100;000 - #200;000,Disposable pads;Pantyliners,Lilypad,Satisfied,Price;Comfort;Absorbency;Skin sensitivity,Yes,Maybe; if I understood them better,Day sanitary pads;Night pads;Wipes;Disposable ...,#801 - #1;200,Supermarket,Yes,No,Nil,Positive Feedback / No Issues / Nil
144,98,25-34,Enugu,Employed,#100;000 - #200;000,Disposable pads;Pantyliners,Molped;Virony;Softcare,Very satisfied,Comfort;Absorbency;Skin sensitivity;Availabili...,Maybe,Maybe; if I understood them better,Day sanitary pads;Night pads;Wipes;Disposable ...,#801 - #1;200,Supermarket,Maybe,Yes,Nothing really at the moment,Positive Feedback / No Issues / Nil
145,99,25-34,Abuja,Employed,#100;000 - #200;000,Disposable pads,Softcare,Very satisfied,Comfort;Absorbency;Skin sensitivity,Maybe,No,Day sanitary pads;Night pads;Wipes;Disposable ...,Over #1;200,Supermarket,Maybe,Maybe,Comfort,Comfort & Skin Sensitivity

In [25]:
# Export to Excel
df_exploded.to_excel("menstrual_themes_exploded.xlsx", index=False)