In [1]:
import pandas as pd
df = pd.read_csv('Product Audit Table—Feminine Hygiene Products (Abuja).csv')

In [2]:
df.columns

Index(['Entry_id', 'State',
       'Store Name: Name of supermarket, pharmacy, or stall ',
       'Location: address and area ',
       'Product Brand Name: E.g., Always, Molped, LadyCare ',
       'Variants Available: Regular, night, long, etc. ',
       'Product Size: Total number of items in the pack ', 'Length(mm)',
       'Price (#): Current shelf price (not promo price) ',
       'Packaging Description: What does the packaging look/feel like? ',
       'Key Claims on Pack: E.g., leak protection, ultra-thin, odor control ',
       'Eco-friendly Option: Yes/No (Does it promote sustainability?) ',
       'Shelf Placement: Top / Mid / Bottom / Hidden ',
       'Visibility Rating: Low / Medium / High (Based on ease of spotting) ',
       'Promo Offer: Any discounts, bonus packs, or gift items? ',
       'Top Seller?: Input from vendor on sales rank or popularity ',
       'Notes/Remarks: Other relevant info (e.g., product out of stock, observed consumer behavior) '],
      dtype='object')

In [7]:
def classify_packaging_multi(text):
    if pd.isna(text):
        return 'Missing'

    text = text.lower()
    categories = []

    if any(k in text for k in ['yellow', 'purple', 'pink', 'colour', 'color', 'green', 'white', 'blue']):
        categories.append('Color-Focused')

    if any(k in text for k in ['portable', 'rectangular', 'compact', 'cubic', 'small', 'handy']):
        categories.append('Portable Design')

    if any(k in text for k in ['traditional', 'paper', 'carton']):
        categories.append('Traditional')

    if any(k in text for k in ['exotic', 'unique', 'fancy', 'attractive', 'night', 'mint', 'shower bag']):
        categories.append('Exotic or Unique')

    if any(k in text for k in ['feminine', 'fine', 'girly']):
        categories.append('Feminine Design')

    if any(k in text for k in ['besense', 'softcare', 'same as']):
        categories.append('Brand Comparison')

    if any(k in text for k in ['okay', 'good', 'nil', 'refer to earlier entries', 'same packaging', 'same as other']):
        categories.append('Unspecified/Generic')

    if 'different designs for different variants' in text:
        categories.append('Unspecified/Generic')

    return '; '.join(categories) if categories else 'Other'

# Apply the function to your packaging column
df['Packaging_Classifications'] = df['Packaging Description: What does the packaging look/feel like? '].apply(classify_packaging_multi)

In [3]:
df

,Entry_id,State,"Store Name: Name of supermarket, pharmacy, or stall",Location: address and area,"Product Brand Name: E.g., Always, Molped, LadyCare","Variants Available: Regular, night, long, etc.",Product Size: Total number of items in the pack,Length(mm),Price (#): Current shelf price (not promo price),Packaging Description: What does the packaging look/feel like?,"Key Claims on Pack: E.g., leak protection, ultra-thin, odor control",Eco-friendly Option: Yes/No (Does it promote sustainability?),Shelf Placement: Top / Mid / Bottom / Hidden,Visibility Rating: Low / Medium / High (Based on ease of spotting),"Promo Offer: Any discounts, bonus packs, or gift items?",Top Seller?: Input from vendor on sales rank or popularity,"Notes/Remarks: Other relevant info (e.g., product out of stock, observed consumer behavior)"
0,1,Abuja,Novare Mall,Lugbe,Angel,No,10,280.0,"2,150",Portable and feminine colour combo,"Soft cover, long flexi wings, super absorbent",Yes,Top,high,No,NaN,Imported
1,2,Abuja,Novare mall,Lugbe,Ladycare,No,10,NaN,"1,250",Yellow,Now longer,Yes,Middle,medium,No,NaN,Manufactured in Nigeria
2,3,Abuja,Sahad stores,Area 11,Softcare,Regular,10,NaN,3800,Attractive purple design,"Cotton feel, 3D comfort fit, Freely breathe",Yes,Top,high,No,NaN,The highest in quantity on shelves/ manufactur...
3,4,Abuja,Sahad stores,Area 11,7-layer,Night,10,NaN,2600,Night feel,Super soft cotton,Yes,Middle,medium,No,NaN,Foreign made
4,5,Abuja,Sahad stores,Area 11,Molped,Regular,8,NaN,1200,Different designs for different variants,"Cotton cover, skin friendly",Yes,Middle,medium,No,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,74,Abuja,UniAbuja,UniAbuja,Molped,Extra long,9,NaN,900,Different designs for different variants,"Cotton cover, skin friendly",Yes,Top,high,No,NaN,NaN
74,75,Abuja,UniAbuja,UniAbuja,Softcare,Regular,10,NaN,1200,Attractive purple design,"Cotton feel, 3D comfort fit, Freely breathe",Yes,Top,high,No,NaN,NaN
75,76,Abuja,UniAbuja,UniAbuja,Always (3-in-1),Long,7,NaN,1500,Portable,"No leaks, irritation and scent worries",Yes,Top,high,No,NaN,NaN
76,77,Abuja,UniAbuja,UniAbuja,Ladycare,Regular,10,NaN,900,Traditional,Now longer,Yes,Middle,high,No,NaN,NaN
77,78,Abuja,UniAbuja,UniAbuja,My Girl,Long,8,NaN,650,Refer to earlier entries,Refer to earlier entries,Yes,Middle,medium,No,NaN,NaN

In [8]:
df_packaging = pd.DataFrame({
    "Index": range(1, len(df) + 1),
    "Packaging Description": df['Packaging Description: What does the packaging look/feel like? '],
    "Packaging_Classifications": df['Packaging_Classifications']
})
df_packaging

,Index,Packaging Description,Packaging_Classifications
0,1,Portable and feminine colour combo,Color-Focused; Portable Design; Feminine Design
1,2,Yellow,Color-Focused
2,3,Attractive purple design,Color-Focused; Exotic or Unique
3,4,Night feel,Exotic or Unique
4,5,Different designs for different variants,Unspecified/Generic
...,...,...,...
73,74,Different designs for different variants,Unspecified/Generic
74,75,Attractive purple design,Color-Focused; Exotic or Unique
75,76,Portable,Portable Design
76,77,Traditional,Traditional
77,78,Refer to earlier entries,Unspecified/Generic

In [9]:
df_packaging.columns

Index(['Index', 'Packaging Description', 'Packaging_Classifications'], dtype='object')

In [10]:
# Step 1: First, split the semicolon-separated themes into a list
df_packaging['Packaging_Classifications'] = df_packaging['Packaging_Classifications'].str.split("; ")
df_packaging

,Index,Packaging Description,Packaging_Classifications
0,1,Portable and feminine colour combo,"[Color-Focused, Portable Design, Feminine Design]"
1,2,Yellow,[Color-Focused]
2,3,Attractive purple design,"[Color-Focused, Exotic or Unique]"
3,4,Night feel,[Exotic or Unique]
4,5,Different designs for different variants,[Unspecified/Generic]
...,...,...,...
73,74,Different designs for different variants,[Unspecified/Generic]
74,75,Attractive purple design,"[Color-Focused, Exotic or Unique]"
75,76,Portable,[Portable Design]
76,77,Traditional,[Traditional]
77,78,Refer to earlier entries,[Unspecified/Generic]

In [12]:
packaging_description_exploded = df_packaging.explode('Packaging_Classifications').reset_index(drop=True)
packaging_description_exploded

    Index               Packaging Description Packaging_Classifications
0       1  Portable and feminine colour combo             Color-Focused
1       1  Portable and feminine colour combo           Portable Design
2       1  Portable and feminine colour combo           Feminine Design
3       2                             Yellow              Color-Focused
4       3            Attractive purple design             Color-Focused
..    ...                                 ...                       ...
89     75            Attractive purple design             Color-Focused
90     75            Attractive purple design          Exotic or Unique
91     76                            Portable           Portable Design
92     77                        Traditional                Traditional
93     78            Refer to earlier entries       Unspecified/Generic

[94 rows x 3 columns]

In [13]:
#saving th excel file
packaging_description_exploded.to_csv('packaging_description_exploded.csv', index = False)

In [14]:
# Packaging claims
claims = [
    "Soft cover, long flexi wings, super absorbent",
    "Now longer",
    "Cotton feel, 3D comfort fit, Freely breathe",
    "Super soft cotton",
    "Cotton cover, skin friendly",
    "Cotton cover, skin friendly",
    "Cotton cover, skin friendly",
    "Ultra thin, natural mint, dryness",
    "Ultra thin, natural mint, dryness",
    "Ultra thin, natural mint, dryness",
    "Leak lock, comfortable and ventilatory",
    "Dryness, Natural mint, Ultra thin",
    "Ultra thin, breathable, natural mint, dryness",
    "Breathable and comfortable",
    "Extra long, extra soft, total odour control, ultra absorption, leakage protection layer",
    "As contained on lily pad maxi comfort",
    "Now longer",
    "Up to 100% leak protection",
    "With Antibacterial Protection",
    "Same claim as other lilypads",
    "Instantdry, leakguard, odourlock",
    "No leaks, irritation and scent worries",
    "As seen in same brand at SAHAD stores",
    "Air Breath",
    "Absorbs 3x of its weight",
    "Mentholated Sanitary pad",
    "Ultra slim pads with Anion chips",
    "Now longer",
    "With wings",
    "3in1, no leaks, irritation and scent",
    "With wings",
    "Super Absorbent to give you confidence, Extra long and extra thin, No harmful Chemicals",
    "20% extra absorption",
    "Perfect protection/ Ultra soft",
    "Already recorded at Sahad stores",
    "No double ups",
    "No Double Ups",
    "Now longer",
    "With mint, naturally absorbent, prevents skin irritation",
    "Safer, wider, scented",
    "No leaks",
    "Absorbs 70% faster, 100% cotton and waterproof, protection and odor neutralization",
    "Absorbs 60% faster, super thin",
    "Extra",
    "Ultra thin",
    "Curve comfort fit, Super dry, free from fragrance",
    "Cotton cover, skin friendly",
    "Cotton cover, skin friendly",
    "Up to 100% leak protection",
    "Up to 100% leak protection",
    "Perfect protection",
    "Perfect protection",
    "Perfect protection",
    "Perfect protection",
    "Now longer",
    "Cotton feel, 3D comfort fit, Freely breathe",
    "Cotton cover, skin friendly",
    "Maxi comfort",
    "Ultra slim",
    "Extra thin",
    "Ultra soft",
    "No leaks, irritation & scent",
    "Complete protection",
    "Naturally absorbent",
    "Now longer",
    "Maxi comfort",
    "Refer to the previous entries",
    "Absorbs 60% faster, super thin",
    "Ultra thin, natural mint, dryness",
    "Cotton cover, skin friendly",
    "Now longer",
    "Refer to earlier entries on this",
    "Cotton cover, skin friendly",
    "Cotton cover, skin friendly",
    "Cotton feel, 3D comfort fit, Freely breathe",
    "No leaks, irritation and scent worries",
    "Now longer",
    "Refer to earlier entries"
]

# Multi-label classification function
def multi_classify_claim(claim):
    claim_lower = claim.lower()
    tags = []

    # Define classification rules
    if any(x in claim_lower for x in ["absorb", "absorbs", "extra absorption", "3x", "super absorbent", "ultra absorption"]):
        tags.append("Good absorbency")
    if any(x in claim_lower for x in ["leak", "leak protection", "no leaks", "leakguard", "leak lock"]):
        tags.append("Leak Protection")
    if any(x in claim_lower for x in ["comfort", "super soft", "ultra soft", "perfect protection", "curve comfort", "freely breathe"]):
        tags.append("Comfortable")
    if any(x in claim_lower for x in ["cotton", "skin friendly", "cotton feel", "soft cover"]):
        tags.append("skin friendly")
    if any(x in claim_lower for x in ["mint", "natural", "menthol", "anion", "antibacterial"]):
        tags.append("Natural/Mint")
    if any(x in claim_lower for x in ["wings", "structure", "double ups"]):
        tags.append("Wings/Structure")
    if any(x in claim_lower for x in ["scent", "odor", "odour", "fragrance"]):
        tags.append("odor Control")
    if any(x in claim_lower for x in ["same", "refer", "already recorded", "as seen"]):
        tags.append("unclassifed")
    if any(x in claim_lower for x in ["ultra thin", "super thin", "extra thin", "ultra slim"]):
        tags.append("Thin Design")
    
    if not tags:
        tags.append("Other")
    
    return tags

# Build DataFrame
df_claims = pd.DataFrame({
    "Index": range(1, len(claims)+1),
    "Packaging_Description": claims
})

# Apply multi-classification
df_claims["Tags"] = df_claims["Packaging_Description"].apply(multi_classify_claim)

# # Optional: expand into separate binary columns
# df_expanded = df_claims.explode("Tags").pivot_table(index="Index", columns="Tags", aggfunc=lambda x: 1, fill_value=0)
# df_final = df_claims.join(df_expanded, on="Index")

# Preview
df_claims.head(10)

,Index,Packaging_Description,Tags
0,1,"Soft cover, long flexi wings, super absorbent","[Good absorbency, skin friendly, Wings/Structure]"
1,2,Now longer,[Other]
2,3,"Cotton feel, 3D comfort fit, Freely breathe","[Comfortable, skin friendly]"
3,4,Super soft cotton,"[Comfortable, skin friendly]"
4,5,"Cotton cover, skin friendly",[skin friendly]
5,6,"Cotton cover, skin friendly",[skin friendly]
6,7,"Cotton cover, skin friendly",[skin friendly]
7,8,"Ultra thin, natural mint, dryness","[Natural/Mint, Thin Design]"
8,9,"Ultra thin, natural mint, dryness","[Natural/Mint, Thin Design]"
9,10,"Ultra thin, natural mint, dryness","[Natural/Mint, Thin Design]"

In [16]:
claims = df_claims.explode('Tags').reset_index(drop=True)

In [17]:
claims.to_csv('claims_exploded.csv', index = False)